server:
  port: 8081
  servlet:
    context-path: /hello
spring:
  profiles:
    active: prod
---
server:
  port: 8082
spring:
  profiles: dev

---
server:
  port: 8083
spring:
  profiles: prod
---

person:
  last-name: 89412199@qq.com
  age: ${random.int}
  birth: 2010/10/10
  lists: [aa,bb]
  boss: false
  dog: {name: abc, age: 3}
  maps: {k1: v1, k2: v2}
debug: true